apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-container
        image: harsh672/healthcare-application
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-eta-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app

  type: NodePort
  ports:
  - nodePort: 30000   
    port: 8084
    targetPort: 8084
